### ISSUE TITLE
env: node\r: No such file or directory

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [ognjengt/build-express-api#2]
Run `build-express-api init` outputs:

```
env: node\r: No such file or directory
```
I am using macOS 10.13.1.

**Comment by ognjengt** [comment]
Interesting, will look into that.

**Comment by ognjengt** [comment]
Solved.

**Comment by TravisL12** [comment]
I had this problem too and found in other searches to open:
`~/.nvm/versions/node/v10.9.0/lib/node_modules/build-express-api/bin/cli.js` with `vim`

Then use commands:
`:set ff=unix <enter>`
`:x <enter>`

And the `init` command then worked.

**Comment by ognjengt** [comment]
Thank you, Travis, I will look into fixing the issue.
